### ISSUE TITLE
Cannot place floor tiles above Large Furnaces.

### ISSUE THREAD

**Issue by Work-Safe-Reddit4450** [pfergus/Fortify#3]
Currently, in Rust, you are able to place Floor Frames and Floor Tiles 1 floor above Large Furnaces so long as you have your foundations set high. Otherwise you need to have two floors when your foundations are low to the ground. In Fortify 1.53, this is not possible at all at any height above the Large Furnace. Would love to see the ability to create Large Furnace rooms with overhead floor coverage.

**Comment by pfergus** [comment]
My understanding is that you can't place the furnace with those floors in place but can add them after. Is that correct?
